export const languages = [
    "Mandarin Chinese",
    "Spanish",
    "English",
    "Hindi",
    "Bengali",
    "Portuguese",
    "Russian",
    "Japanese",
    "German",
    "Korean",
    "French",
    "Turkish",
    "Italian",
    "Tamil",
    "Arabic",
    "Urdu",
    "Indonesian",
    "Swahili",
    "Dutch",
    "Polish",
    "Thai",
    "Vietnamese",
    "Persian",
    "Greek",
    "Swedish",
    "Czech",
    "Hungarian",
    "Hebrew",
    "Danish",
    "Finnish",
  ];

  