export const roles = [
    "CEO",
    "CTO",
    "Software Engineer",
    "Web Developer",
    "Frontend Developer",
    "Backend Developer",
    "Full Stack Developer",
    "Mobile App Developer",
    "Data Scientist",
    "Data Analyst",
    "Database Administrator",
    "Network Administrator",
    "Systems Administrator",
    "DevOps Engineer",
    "Cloud Architect",
    "UI/UX Designer",
    "Product Manager",
    "Project Manager",
    "Quality Assurance Engineer",
    "Security Engineer",
    "IT Support Specialist",
    "IT Operations Manager",
    "IT Consultant",
    "Business Analyst",
    "Technical Writer",
    "Sales Engineer",
    "Marketing Manager",
    "Human Resources Manager",
    "Finance Manager",
    "Legal Counsel",
  ];
  